using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Telegram.Bot.Ext.SourceGenerators.Utils;

namespace Telegram.Bot.Ext.SourceGenerators;

[Generator]
public class TelegramBotExtensionsRepeatSameSourceGenerator : ISourceGenerator
{
    private const string TelegramBotAssemblyName = "Telegram.Bot";
    private const string ClassName = "TelegramBotClientExt";

    private static readonly HashSet<string> ExcludedMethods = new() {
        "StartReceiving", "ReceiveAsync", "GetType", "ToString", "Equals", "GetHashCode",
    };

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var telegramBotAssemblyIdentity =
            context.Compilation.SourceModule.ReferencedAssemblies.First(a => a.Name == TelegramBotAssemblyName);
        var telegramBotReference =
            context.Compilation.References.First(r => r.Display?.Contains(TelegramBotAssemblyName) == true);
        var telegramBotAssembly = Assembly.LoadFrom(((PortableExecutableReference)telegramBotReference).FilePath!);
        if (telegramBotAssemblyIdentity.Version != telegramBotAssembly.GetName().Version)
            throw new InvalidOperationException($"Versions of {TelegramBotAssemblyName} are different");

        var telegramBotClientExtensionsType =
            telegramBotAssembly.ExportedTypes.First(t => t.Name == "TelegramBotClientExtensions");

        var sb = new StringBuilder();
        AppendClass(sb, true);

        foreach (var methodInfo in telegramBotClientExtensionsType.GetMethods())
        {
            if (ExcludedMethods.Contains(methodInfo.Name))
                continue;

            var parameters = methodInfo.GetParameters();
            AppendMethod(sb, methodInfo, parameters);
        }

        AppendClass(sb, false);

        var resultCode = CSharpSyntaxTree.ParseText(sb.ToString()).GetRoot().NormalizeWhitespace().SyntaxTree
            .GetText().ToString();
        context.AddSource($"{ClassName}.g.cs", SourceText.From(resultCode, Encoding.UTF8));
    }

    private static void AppendClass(StringBuilder sb, bool isStart)
    {
        sb.Append(isStart
            ? $@"
              // <auto-generated/>

              namespace Telegram.Bot.Ext
              {{
                  public static partial class {ClassName}
                  {{
              "
            : @"
                  }
              }
              ");
    }

    private static void AppendMethod(StringBuilder sb, MethodInfo methodInfo, ParameterInfo[] parameters)
    {
        var returnTypeName = methodInfo.ReturnType.GetFullName();
        var generatingParameters = parameters.Skip(1).ToList();
        sb.Append($@"
                    public static {returnTypeName} {methodInfo.Name}(
                        this ITelegramBot bot,");
        foreach (var parameterInfo in generatingParameters)
        {
            sb.Append($"{parameterInfo.ParameterType.GetFullName()} {parameterInfo.Name}{(parameterInfo.IsOptional ? " = default" : "")},");
        }

        sb.Length--;
        sb.Append($@"
                   )
                      => bot.Client.{methodInfo.Name}(
                  ");
        foreach (var parameterInfo in generatingParameters)
        {
            sb.Append($"{parameterInfo.Name},");
        }
        sb.Length--;
        sb.Append(");");
    }
}
